# Generated by Django 5.2.14 on 2026-05-25 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('admin', 'Administrateur')], default='etudiant', max_length=20)),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.filiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre du projet')),
                ('type_projet', models.CharField(choices=[('rapport_stage', 'Rapport de Stage'), ('pfe', "Projet de Fin d'Études"), ('memoire', 'Mémoire'), ('these', 'Thèse'), ('tp', 'Travail Pratique'), ('autre', 'Autre')], max_length=30, verbose_name='Type')),
                ('niveau', models.CharField(choices=[('licence1', 'Licence 1'), ('licence2', 'Licence 2'), ('licence3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2'), ('doctorat', 'Doctorat')], max_length=20, verbose_name='Niveau')),
                ('encadreur', models.CharField(blank=True, max_length=200, verbose_name='Encadreur')),
                ('annee', models.IntegerField(default=2026, verbose_name='Année académique')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('mots_cles', models.CharField(blank=True, max_length=500, verbose_name='Mots-clés')),
                ('fichier', models.FileField(upload_to='projets/%Y/%m/', verbose_name='Fichier (PDF)')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couvertures/', verbose_name='Image de couverture')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('archive', 'Archivé')], default='en_attente', max_length=20)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Note /20')),
                ('vues', models.PositiveIntegerField(default=0)),
                ('telechargements', models.PositiveIntegerField(default=0)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('note', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approuve', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='archives.projet')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['-date'],
            },
        ),
    ]
